config/routes.rb
GumdoVocab::Application.routes.draw do
  get "gumdo_vocabulary/index"

  match 'start_game' => 'gumdo_vocabulary#start_game', :as => :start_game
  match 'next_question' => 'gumdo_vocabulary#next_question', :as => :next_question
  match '/games/:id/question/:number' => 'games#get_question', :as => :get_question
  match '/games/:id/question/:number/answer/:answer' => 'games#check_answer', :as => :check_answer

  resources :vocab_terms
  resources :games

  root :to => "gumdo_vocabulary#index"

  
end

app/models/game.rb
class Game < ActiveRecord::Base
  serialize :questions, Array
  serialize :answers, Array
  serialize :categories, Array
  
  def is_easy?
    self.difficulty == "easy"
  end
end

app/models/vocab_term.rb
class VocabTerm < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def create
    @game = Game.new
    @game.questions = Array.new
    @game.answers = Array.new
    @questions_total = params[:questions_total].to_i
    @questions_total ||= 10
    @game.difficulty = params[:difficulty]
    @game.difficulty ||= "easy"
    @game.categories = params[:categories]
    
    VocabTerm.where(:category => params[:categories]).shuffle.sample(@questions_total).each do |term|
      @game.questions << term.id
    end
    
    respond_to do |format|
      if @game.save
        format.html {redirect_to(@game)}
      end
    end
  end
  
  def new
    @game = Game.new
    @vocab_categories = Array.new
    VocabTerm.select(:category).each do |term|
      @vocab_categories << term.category if !@vocab_categories.include? term.category
    end
    @vocab_categories.sort!.uniq!
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @game = Game.find(params[:id])
    
    respond_to do |format|
      format.html
    end
  end
  
  def get_question
    @game = Game.find(params[:id])
    @vocab_id = @game.questions[params[:number].to_i - 1]
    @vocab = VocabTerm.find @vocab_id if !@vocab_id.nil?
    
    respond_to do |format|
      if !@vocab_id.nil?
        format.js
      else
        format.js {render "summary"}
      end
    end
  end
  
  def check_answer
    @game = Game.find(params[:id])
    @vocab_id = @game.questions[params[:number].to_i - 1]
    
    respond_to do |format|
      if(@vocab_id.to_s == params[:answer])
        @game.answers[params[:number].to_i - 1] = 1
        @game.save
        format.html {render :text => "correct"}
      else
        @game.answers[params[:number].to_i - 1] = 0
        @game.save
        format.html {render :text => @vocab_id.to_s}
      end
    end
  end
end

app/controllers/gumdo_vocabulary_controller.rb
class GumdoVocabularyController < ApplicationController
  def index
    
  end
  
  def start_game
    @questions_total = 10
    @question_count = 1
    @terms = VocabTerm.all.shuffle.sample(@questions_total)
    @english_terms = VocabTerm.select("id, english");
    render 'game'
  end
  
  def check_answer
    
  end
  
  def next_question
    #@question_count += 1
    render 'game'
  end

end

app/controllers/vocab_terms_controller.rb
class VocabTermsController < ApplicationController
  def index
    @vocab_terms = VocabTerm.all
    
    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @vocab_terms }
    end
  end
  
  def create
    @vocab_term = VocabTerm.new(params[:post])
 
    respond_to do |format|
      if @vocab_term.save
        format.html  { redirect_to(@vocab_term,
                      :notice => 'Term was successfully created.') }
        format.json  { render :json => @vocab_term,
                      :status => :created, :location => @vocab_term }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @vocab_term.errors,
                      :status => :unprocessable_entity }
      end
    end
  end
  
  def new
    @vocab_term = VocabTerm.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @vocab_term}
    end
  end
  
  def edit
    @vocab_term = VocabTerm.find(params[:id])
  end
  
  def show
    @vocab_term = VocabTerm.find(params[:id])
 
    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @vocab_term }
    end
  end
  
  def update
    @vocab_term = VocabTerm.find(params[:id])
 
    respond_to do |format|
      if @vocab_term.update_attributes(params[:vocab_term])
        format.html  { redirect_to(@vocab_term,
                      :notice => 'Term was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @vocab_term.errors,
                      :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/gumdo_vocabulary_helper.rb
module GumdoVocabularyHelper
end

app/helpers/vocab_terms_helper.rb
module VocabTermsHelper
end

app/views/games/_summary.html.haml
%p= "You Scored #{number_to_percentage((game.answers.count(1).to_f / game.answers.count) * 100, :precision=>0)}"
%table
  - (0...game.answers.count).to_a.in_groups_of(2).each do |index_group|
    %tr
      - index_group.each do |index|
        - term = VocabTerm.find(game.questions[index]) unless index.nil?
        %td= game.answers[index] == 1 ? image_tag("/images/correct.jpeg") : image_tag("/images/incorrect.jpeg")
        %td= term.korean + ": " + term.english

app/views/games/get_question.js.erb
$('#centerdiv').html("<%= escape_javascript(
	render :partial=>'vocab_terms/question', 
		:locals=>{:term=>@vocab, :number=>params[:number], :game=>@game}
) %>")

$(document).ready(function(){
	var term_id = <%= escape_javascript(@vocab.id.to_s)%>
	
	$('li').on('click', function(){
		var elm = $(this)
		$.ajax({
			url: "<%= escape_javascript(request.env['PATH_INFO'])%>" + "/answer/" + $(this).attr('id'),
			success: function(data){
				if(data == "correct"){
					elm.addClass('correct')
				} else {
					term_id = data;
					elm.addClass('incorrect')
					$('li#'+term_id).addClass('correct')
				}
				$('li').unbind();
				$('.next_question_button').toggle();
			}
		});
	});
	
	$('.sound').live('click', function () {  

    	if(window.chrome) this.load();
		this.play();
    	return false;
	});
});

app/views/games/new.html.haml
= form_for @game do |f|
  %h1 How Many Questions:
  = number_field_tag "questions_total", 10
  %h1 Difficulty:
  = radio_button_tag "difficulty", "easy", true
  = label_tag "difficulty_easy", "Easy"
  = radio_button_tag "difficulty", "hard"
  = label_tag "difficulty_hard", "Hard"
  %h1 Select Your Categories:
  - @vocab_categories.each do |category|
    = check_box_tag "categories[#{category}]", category, true, :name=>"categories[]"
    = label_tag "categories[#{category}]", category
  #button_div= f.submit

app/views/games/show.html.haml
#leftdiv
#centerdiv
  %p All Right! Get Ready To Start
  = button_to 'Start Game', get_question_path(@game,1), :remote=>true, :method=>:get
#rightdiv

app/views/games/summary.js.erb
$('#centerdiv').html("<%= escape_javascript(
	render :partial=>'summary', 
		:locals=>{:game=>@game}
) %>")

app/views/gumdo_vocabulary/index.html.erb
<h1>Welcome to the Gumdo Vocabulary Game</h1>

<%= link_to "Start Game", new_game_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GumdoVocab</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="container">
	<div id="header">
		<h1>Gumdo Vocabulary</h1>
	</div>
	<div id="content_container">
		<%= yield %>
	</div>
	<div id="footer">
        
    </div>
</div>
</body>
</html>

app/views/vocab_terms/_form.html.erb
<%= form_for(@vocab_term) do |f| %>
  <% if @vocab_term.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@vocab_term.errors.count, "error") %> prohibited this term from being saved:</h2>
    <ul>
    <% @vocab_term.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :english %><br />
    <%= f.text_field :english %>
  </div>
  <div class="field">
    <%= f.label :korean %><br />
    <%= f.text_field :korean %>
  </div>
  <div class="field">
    <%= f.label :romanized %><br />
    <%= f.text_field :romanized %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :audio_source %><br />
    <%= f.text_field :audio_source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vocab_terms/_question.html.haml
- answers = VocabTerm.select("id, english").where(:category => game.categories).sample(3)
- answers << term
%p= "Question #{number} of 10"
#question
  %h1= term.korean
  %table.audio_wrapper
    %tr
      %td
        = audio_tag(term.audio_source, :auto_play=>false, :controls=>true, :class=>"sound")
  %h3= term.romanized if game.is_easy?
#answers
  %ul
    - answers.shuffle.each do |answer|
      %li{:id=>answer.id}= answer.english
.next_question_button
  = button_to "Next Question", get_question_path(game, number.to_i + 1), :method=>:get, :remote=>true

app/views/vocab_terms/edit.html.erb
<h1>Edit Vocab Term</h1>
 
<%= render 'form' %>
 
<%= link_to 'Show', @vocab_term %> 
<%= link_to 'Back', vocab_terms_path %>

app/views/vocab_terms/index.html.erb
<h1>Listing Vocab Terms</h1>

<table>
  <tr>
    <th>ID</th>
    <th>English</th>
    <th>Korean</th>
    <th>Romanized</th>
    <th>Category</th>
    <th>Audio Source</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @vocab_terms.each do |term| %>
  <tr>
    <td><%= term.id %></td>
    <td><%= term.english %></td>
    <td><%= term.korean %></td>
    <td><%= term.romanized %></td>
    <td><%= term.category %></td>
    <td><%= term.audio_source %></td>
    <td><%= link_to 'Show', term %></td>
    <td><%= link_to 'Edit', edit_vocab_term_path(term) %></td>
    <td><%= link_to 'Destroy', term, :confirm => 'Are you sure?',
                                     :method => :delete %></td>
  </tr>
<% end %>
</table>
 
<br />
 
<%= link_to 'New Vocab Term', new_vocab_term_path %>

app/views/vocab_terms/new.html.erb
<h1>New Vocab Term</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', vocab_terms_path %>

app/views/vocab_terms/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <b>English:</b>
  <%= @vocab_term.english %>
</p>
 
<p>
  <b>Korean:</b>
  <%= @vocab_term.korean %>
</p>
 
<p>
  <b>Romanized:</b>
  <%= @vocab_term.romanized %>
</p>

<p>
  <b>Category:</b>
  <%= @vocab_term.category %>
</p>

<p>
  <b>Audio Source:</b>
  <%= @vocab_term.audio_source %>
</p>

<p>
	<%= audio_tag(@vocab_term.audio_source, :auto_play=>false, :controls=>true)%>
</p>
<%= link_to "Google Translate Pronunciation", "http://translate.google.com/translate_tts?tl=ko&q="+@vocab_term.korean %>
<br/>
<%= link_to 'Edit', edit_vocab_term_path(@vocab_term) %> |
<%= link_to 'Back', vocab_terms_path %>